# Generated by Django 5.0.6 on 2026-07-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='项目编号')),
                ('current_stage', models.IntegerField(choices=[(1, '构思中'), (2, '已立项'), (3, '材料准备中'), (4, '开发实验制作中'), (5, '报名准备'), (6, '材料提交'), (7, '网评审核'), (8, '答辩准备'), (9, '校赛'), (10, '市赛'), (11, '省赛'), (12, '国赛'), (13, '已获奖'), (14, '已结项'), (15, '暂停'), (16, '终止')], default=1, verbose_name='当前阶段')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('planned_end_date', models.DateField(blank=True, null=True, verbose_name='计划结束日期')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='实际结束日期')),
                ('status', models.CharField(choices=[('active', '进行中'), ('paused', '暂停'), ('closed', '已关闭')], default='active', max_length=20, verbose_name='项目状态')),
                ('priority', models.CharField(choices=[('normal', '普通'), ('high', '高'), ('urgent', '紧急')], default='normal', max_length=20, verbose_name='优先级')),
                ('intro', models.TextField(blank=True, default='', verbose_name='项目简介')),
                ('last_leader_update', models.DateTimeField(blank=True, null=True, verbose_name='负责人最近更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_project', models.CharField(choices=[('leader', '负责人'), ('core', '核心成员'), ('participant', '普通参与')], default='participant', max_length=20, verbose_name='项目角色')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
            ],
            options={
                'verbose_name': '项目成员',
                'verbose_name_plural': '项目成员',
                'db_table': 'project_members',
            },
        ),
        migrations.CreateModel(
            name='ProjectStageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.IntegerField(blank=True, choices=[(1, '构思中'), (2, '已立项'), (3, '材料准备中'), (4, '开发实验制作中'), (5, '报名准备'), (6, '材料提交'), (7, '网评审核'), (8, '答辩准备'), (9, '校赛'), (10, '市赛'), (11, '省赛'), (12, '国赛'), (13, '已获奖'), (14, '已结项'), (15, '暂停'), (16, '终止')], null=True, verbose_name='原阶段')),
                ('to_stage', models.IntegerField(choices=[(1, '构思中'), (2, '已立项'), (3, '材料准备中'), (4, '开发实验制作中'), (5, '报名准备'), (6, '材料提交'), (7, '网评审核'), (8, '答辩准备'), (9, '校赛'), (10, '市赛'), (11, '省赛'), (12, '国赛'), (13, '已获奖'), (14, '已结项'), (15, '暂停'), (16, '终止')], verbose_name='目标阶段')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '项目阶段日志',
                'verbose_name_plural': '项目阶段日志',
                'db_table': 'project_stage_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
