# Generated by Django 5.0.6 on 2026-07-07 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_add_soft_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('reviewed', '已审阅')], default='draft', max_length=20, verbose_name='状态')),
                ('summary', models.TextField(blank=True, default='', verbose_name='项目总结')),
                ('achievements', models.TextField(blank=True, default='', verbose_name='主要成果')),
                ('problems', models.TextField(blank=True, default='', verbose_name='遇到的问题')),
                ('lessons', models.TextField(blank=True, default='', verbose_name='经验教训')),
                ('improvements', models.TextField(blank=True, default='', verbose_name='改进建议')),
                ('team_feedback', models.TextField(blank=True, default='', verbose_name='团队反馈')),
                ('overall_score', models.IntegerField(blank=True, null=True, verbose_name='总体评分')),
                ('schedule_score', models.IntegerField(blank=True, null=True, verbose_name='进度管理评分')),
                ('budget_score', models.IntegerField(blank=True, null=True, verbose_name='经费管理评分')),
                ('team_score', models.IntegerField(blank=True, null=True, verbose_name='团队协作评分')),
                ('quality_score', models.IntegerField(blank=True, null=True, verbose_name='成果质量评分')),
                ('review_date', models.DateTimeField(blank=True, null=True, verbose_name='复盘日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='projects.project', verbose_name='关联项目')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_projects', to=settings.AUTH_USER_MODEL, verbose_name='复盘人')),
            ],
            options={
                'verbose_name': '项目复盘',
                'verbose_name_plural': '项目复盘',
                'db_table': 'project_reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
