# Generated by Django 5.0.6 on 2026-07-07 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_archived_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('is_completed', models.BooleanField(default=False, verbose_name='已完成')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目里程碑',
                'verbose_name_plural': '项目里程碑',
                'db_table': 'milestones',
                'ordering': ['sort_order', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='风险标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='风险描述')),
                ('level', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '严重')], default='medium', max_length=20, verbose_name='风险级别')),
                ('status', models.CharField(choices=[('open', '开放'), ('mitigating', '处理中'), ('closed', '已关闭')], default='open', max_length=20, verbose_name='状态')),
                ('mitigation_plan', models.TextField(blank=True, default='', verbose_name='缓解措施')),
                ('identified_at', models.DateTimeField(auto_now_add=True, verbose_name='识别时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('identified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identified_risks', to=settings.AUTH_USER_MODEL, verbose_name='识别人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目风险',
                'verbose_name_plural': '项目风险',
                'db_table': 'project_risks',
                'ordering': ['-level', '-identified_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='模板描述')),
                ('category', models.CharField(blank=True, default='', max_length=100, verbose_name='模板类别')),
                ('config', models.JSONField(default=dict, verbose_name='模板配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_templates', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '项目模板',
                'verbose_name_plural': '项目模板',
                'db_table': 'project_templates',
                'ordering': ['-created_at'],
            },
        ),
    ]
