# Generated by Django 6.0.6 on 2026-07-26 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_discussion_knowledge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='exit_reason',
            field=models.TextField(blank=True, default='', verbose_name='退出原因'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='exited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='退出时间'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='handover_notes',
            field=models.TextField(blank=True, default='', verbose_name='交接说明'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='handover_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handover_from_memberships', to='projects.projectmember', verbose_name='项目交接成员'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='status',
            field=models.CharField(choices=[('active', '参与中'), ('on_leave', '暂离'), ('exited', '已退出')], db_index=True, default='active', max_length=20, verbose_name='参与状态'),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='role_in_project',
            field=models.CharField(choices=[('leader', '负责人'), ('core', '核心成员'), ('participant', '普通参与'), ('advisor', '项目顾问'), ('external', '外部协作者')], default='participant', max_length=20, verbose_name='项目角色'),
        ),
        migrations.CreateModel(
            name='ProjectMembershipEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('joined', '加入项目'), ('role_changed', '角色变更'), ('status_changed', '状态变更'), ('exited', '退出项目'), ('reactivated', '重新加入'), ('handover', '项目交接')], max_length=30, verbose_name='事件类型')),
                ('from_role', models.CharField(blank=True, default='', max_length=20, verbose_name='原角色')),
                ('to_role', models.CharField(blank=True, default='', max_length=20, verbose_name='新角色')),
                ('from_status', models.CharField(blank=True, default='', max_length=20, verbose_name='原状态')),
                ('to_status', models.CharField(blank=True, default='', max_length=20, verbose_name='新状态')),
                ('reason', models.TextField(blank=True, default='', verbose_name='原因')),
                ('handover_notes', models.TextField(blank=True, default='', verbose_name='交接说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
                ('handover_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_handover_events', to='projects.projectmember', verbose_name='交接成员')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='projects.projectmember', verbose_name='项目成员关系')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_project_membership_events', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '项目成员变动记录',
                'verbose_name_plural': '项目成员变动记录',
                'db_table': 'project_membership_events',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
