# Generated by Django 5.0.6 on 2026-07-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='文件名称')),
                ('file', models.FileField(upload_to='files/%Y%m/', verbose_name='文件')),
                ('level', models.CharField(choices=[('public', '公开'), ('internal', '内部'), ('sensitive', '敏感')], default='public', max_length=20, verbose_name='权限级别')),
                ('size', models.BigIntegerField(default=0, verbose_name='文件大小')),
                ('content_type', models.CharField(blank=True, default='', max_length=100, verbose_name='内容类型')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文件资源',
                'verbose_name_plural': '文件资源',
                'db_table': 'file_assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/versions/%Y%m/', verbose_name='版本文件')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '文件版本',
                'verbose_name_plural': '文件版本',
                'db_table': 'file_versions',
                'ordering': ['-version'],
            },
        ),
    ]
