# Generated by Django 5.0.6 on 2026-07-01 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fileasset',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='上传人'),
        ),
        migrations.AddField(
            model_name='fileversion',
            name='file_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='files.fileasset', verbose_name='文件资源'),
        ),
        migrations.AddField(
            model_name='fileversion',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_file_versions', to=settings.AUTH_USER_MODEL, verbose_name='上传人'),
        ),
    ]
