# Generated by Django 5.0.6 on 2026-07-07 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_initial'),
        ('projects', '0006_milestone_projectrisk_projecttemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='标签名')),
                ('color', models.CharField(default='#409EFF', max_length=20, verbose_name='颜色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_tags', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_tags', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '文件标签',
                'verbose_name_plural': '文件标签',
                'db_table': 'file_tags',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'project')},
            },
        ),
        migrations.CreateModel(
            name='FileTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_relations', to='files.fileasset', verbose_name='文件')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_relations', to='files.filetag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '文件标签关联',
                'verbose_name_plural': '文件标签关联',
                'db_table': 'file_tag_relations',
                'ordering': ['-created_at'],
                'unique_together': {('file', 'tag')},
            },
        ),
    ]
