# Generated by Django 5.0.6 on 2026-07-26 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_filesharelink'),
        ('projects', '0008_projectmember_exit_reason_projectmember_exited_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fileasset',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='fileasset',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='删除人'),
        ),
        migrations.AddField(
            model_name='fileasset',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='已删除'),
        ),
        migrations.CreateModel(
            name='FileFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='文件夹名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_file_folders', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='files.filefolder', verbose_name='上级文件夹')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_folders', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '文件夹',
                'verbose_name_plural': '文件夹',
                'db_table': 'file_folders',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='fileasset',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='files.filefolder', verbose_name='所在文件夹'),
        ),
        migrations.AddConstraint(
            model_name='filefolder',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('project', 'parent', 'name'), name='uniq_nested_file_folder_name'),
        ),
        migrations.AddConstraint(
            model_name='filefolder',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('project', 'name'), name='uniq_root_file_folder_name'),
        ),
    ]
