# Generated by Django 5.0.6 on 2026-07-07 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0006_milestone_projectrisk_projecttemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('project_created', '创建项目'), ('project_updated', '更新项目'), ('project_closed', '关闭项目'), ('task_created', '创建任务'), ('task_completed', '完成任务'), ('task_updated', '更新任务'), ('file_uploaded', '上传文件'), ('comment_created', '发表评论'), ('member_joined', '成员加入'), ('member_left', '成员离开')], max_length=50, verbose_name='动态类型')),
                ('target_type', models.CharField(default='', max_length=50, verbose_name='目标类型')),
                ('target_id', models.IntegerField(blank=True, null=True, verbose_name='目标ID')),
                ('description', models.CharField(default='', max_length=500, verbose_name='描述')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '动态',
                'verbose_name_plural': '动态',
                'db_table': 'activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
