# Generated by Django 5.0.6 on 2026-07-07 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': '动态', 'verbose_name_plural': '动态'},
        ),
    ]
