# Generated by Django 5.0.6 on 2026-07-07 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_approvalflow_approvalrequest_customform_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('error', '错误'), ('warning', '警告'), ('info', '信息')], default='error', max_length=20, verbose_name='级别')),
                ('message', models.TextField(verbose_name='错误信息')),
                ('stack', models.TextField(blank=True, default='', verbose_name='堆栈')),
                ('url', models.URLField(blank=True, default='', max_length=500, verbose_name='页面URL')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User-Agent')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '前端错误日志',
                'verbose_name_plural': '前端错误日志',
                'db_table': 'error_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
