# Generated by Django 6.0.6 on 2026-07-26 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_errorlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='团队编号'),
        ),
        migrations.AddField(
            model_name='team',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='联系邮箱'),
        ),
        migrations.AddField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='team',
            name='join_message',
            field=models.TextField(blank=True, default='', verbose_name='加入我们说明'),
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='public/team/', verbose_name='团队标志'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='exit_reason',
            field=models.TextField(blank=True, default='', verbose_name='离队原因'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='handover_notes',
            field=models.TextField(blank=True, default='', verbose_name='交接说明'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='handover_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handover_from_members', to='common.teammember', verbose_name='交接成员'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='left_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='离队时间'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='status',
            field=models.CharField(choices=[('active', '在队'), ('on_leave', '暂离'), ('exited', '已离队')], db_index=True, default='active', max_length=20, verbose_name='成员状态'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('owner', '负责人'), ('admin', '团队管理员'), ('teacher', '指导老师'), ('member', '团队成员'), ('advisor', '顾问'), ('external', '外部协作者')], default='member', max_length=50, verbose_name='角色'),
        ),
        migrations.CreateModel(
            name='TeamMembershipEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=30, verbose_name='事件类型')),
                ('from_role', models.CharField(blank=True, default='', max_length=50, verbose_name='原角色')),
                ('to_role', models.CharField(blank=True, default='', max_length=50, verbose_name='新角色')),
                ('from_status', models.CharField(blank=True, default='', max_length=20, verbose_name='原状态')),
                ('to_status', models.CharField(blank=True, default='', max_length=20, verbose_name='新状态')),
                ('reason', models.TextField(blank=True, default='', verbose_name='原因')),
                ('handover_notes', models.TextField(blank=True, default='', verbose_name='交接说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
                ('handover_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_handover_events', to='common.teammember', verbose_name='交接成员')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='common.teammember', verbose_name='团队成员关系')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_team_membership_events', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '团队成员变动记录',
                'verbose_name_plural': '团队成员变动记录',
                'db_table': 'team_membership_events',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
