# Generated by Django 5.0.6 on 2026-07-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_teammember_teacher_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('project_created', '创建项目'), ('project_updated', '更新项目'), ('project_closed', '关闭项目'), ('task_created', '创建任务'), ('task_completed', '完成任务'), ('task_updated', '更新任务'), ('file_uploaded', '上传文件'), ('comment_created', '发表评论'), ('member_joined', '成员加入'), ('member_left', '成员离开'), ('competition_created', '创建比赛参赛条目'), ('competition_updated', '更新比赛参赛条目'), ('competition_awarded', '登记比赛获奖'), ('finance_expense', '登记或更新支出'), ('finance_payment', '完成经费付款'), ('finance_transfer', '登记内部资金转移'), ('finance_income', '登记或更新收入'), ('ip_created', '创建知识产权成果'), ('ip_updated', '更新知识产权成果'), ('ip_authorized', '知识产权成果授权'), ('announcement_published', '发布公告')], max_length=50, verbose_name='动态类型'),
        ),
    ]
