# Generated by Django 5.0.6 on 2026-07-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('system', '系统通知'), ('project', '项目通知'), ('task', '任务通知'), ('finance', '经费通知'), ('competition', '比赛通知'), ('announcement', '公告')], default='system', max_length=20, verbose_name='通知类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('priority', models.CharField(choices=[('low', '低'), ('normal', '普通'), ('high', '高'), ('urgent', '紧急')], default='normal', max_length=20, verbose_name='优先级')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='已读时间')),
                ('related_object_type', models.CharField(blank=True, default='', max_length=50, verbose_name='关联对象类型')),
                ('related_object_id', models.IntegerField(blank=True, null=True, verbose_name='关联对象ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '通知公告',
                'verbose_name_plural': '通知公告',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
