# Generated by Django 5.0.6
"""为 Notification 添加 channel 字段"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='channel',
            field=models.CharField(
                choices=[
                    ('inapp', '站内'),
                    ('email', '邮件'),
                    ('webhook', 'Webhook'),
                ],
                default='inapp',
                max_length=20,
                verbose_name='通知渠道',
            ),
        ),
    ]
