# Generated by Django 5.0.6 on 2026-07-07 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='报表名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('report_type', models.CharField(max_length=50, verbose_name='报表类型')),
                ('config', models.JSONField(default=dict, verbose_name='报表配置')),
                ('is_scheduled', models.BooleanField(default=False, verbose_name='定时生成')),
                ('schedule_cron', models.CharField(blank=True, default='', max_length=100, verbose_name='定时表达式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_reports', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '自定义报表',
                'verbose_name_plural': '自定义报表',
                'db_table': 'custom_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(max_length=20, verbose_name='频率')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='上次运行')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='下次运行')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('recipients', models.ManyToManyField(blank=True, related_name='scheduled_reports', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='exports.customreport', verbose_name='关联报表')),
            ],
            options={
                'verbose_name': '定时报表',
                'verbose_name_plural': '定时报表',
                'db_table': 'scheduled_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
