# Generated by Django 5.0.6 on 2026-07-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledreport',
            name='frequency',
            field=models.CharField(choices=[('daily', '每日'), ('weekly', '每周'), ('monthly', '每月')], default='daily', max_length=20, verbose_name='频率'),
        ),
    ]
