# Generated by Django 6.0.6 on 2026-07-25 16:43

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0002_alter_scheduledreport_frequency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledreport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scheduled_reports', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='day_of_month',
            field=models.PositiveSmallIntegerField(default=1, help_text='1-28，仅每月计划使用。', verbose_name='每月日期'),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='execution_time',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='执行时间'),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='file_format',
            field=models.CharField(choices=[('xlsx', 'Excel'), ('docx', 'Word'), ('pdf', 'PDF')], default='xlsx', max_length=10, verbose_name='文件格式'),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='last_error',
            field=models.TextField(blank=True, default='', verbose_name='最近错误'),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='last_status',
            field=models.CharField(choices=[('never', '尚未运行'), ('running', '运行中'), ('success', '成功'), ('partial', '文件已生成，邮件未发送'), ('failed', '失败')], default='never', max_length=20, verbose_name='最近状态'),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='timezone',
            field=models.CharField(default='Asia/Shanghai', max_length=64, verbose_name='时区'),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='weekday',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 表示周一，6 表示周日，仅每周计划使用。', verbose_name='周几'),
        ),
        migrations.CreateModel(
            name='ScheduledReportExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('manual', '手动'), ('scheduled', '定时')], default='manual', max_length=20, verbose_name='触发方式')),
                ('status', models.CharField(choices=[('never', '尚未运行'), ('running', '运行中'), ('success', '成功'), ('partial', '文件已生成，邮件未发送'), ('failed', '失败')], default='running', max_length=20, verbose_name='状态')),
                ('file', models.FileField(blank=True, null=True, upload_to='scheduled_reports/%Y/%m/', verbose_name='报表文件')),
                ('file_name', models.CharField(blank=True, default='', max_length=255, verbose_name='文件名')),
                ('file_format', models.CharField(blank=True, default='', max_length=10, verbose_name='文件格式')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='文件大小')),
                ('delivery_status', models.CharField(choices=[('not_requested', '未配置接收人'), ('not_configured', '邮件服务未配置'), ('sent', '已发送'), ('failed', '发送失败')], default='not_requested', max_length=30, verbose_name='投递状态')),
                ('recipient_snapshot', models.JSONField(default=list, verbose_name='接收人快照')),
                ('message', models.CharField(blank=True, default='', max_length=500, verbose_name='运行说明')),
                ('error', models.TextField(blank=True, default='', verbose_name='错误详情')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_report_executions', to=settings.AUTH_USER_MODEL, verbose_name='触发人')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='exports.scheduledreport', verbose_name='定时报表')),
            ],
            options={
                'verbose_name': '定时报表执行记录',
                'verbose_name_plural': '定时报表执行记录',
                'db_table': 'scheduled_report_executions',
                'ordering': ['-started_at'],
            },
        ),
    ]
