# Generated by Django 5.0.6 on 2026-07-07 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='看板名称')),
                ('config', models.JSONField(default=dict, verbose_name='看板配置')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认看板')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_dashboards', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '自定义看板',
                'verbose_name_plural': '自定义看板',
                'db_table': 'custom_dashboards',
                'ordering': ['-is_default', '-updated_at'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
