# Generated by Django 5.0.6 on 2026-07-07 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_layout', models.JSONField(blank=True, default=dict, verbose_name='仪表盘布局')),
                ('theme_color', models.CharField(default='blue', max_length=20, verbose_name='主题色')),
                ('default_landing', models.CharField(default='dashboard', max_length=50, verbose_name='默认着陆页')),
                ('sidebar_collapsed', models.BooleanField(default=False, verbose_name='侧边栏默认折叠')),
                ('notification_sound', models.BooleanField(default=True, verbose_name='通知声音')),
                ('items_per_page', models.IntegerField(default=20, verbose_name='每页显示条数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户偏好设置',
                'verbose_name_plural': '用户偏好设置',
                'db_table': 'user_preferences',
            },
        ),
    ]
