# Generated by Django 5.0.6 on 2026-07-07 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_discussion_knowledge'),
        ('users', '0002_user_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='角色名')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('permissions', models.JSONField(default=list, verbose_name='权限列表')),
                ('is_system', models.BooleanField(default=False, verbose_name='系统角色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '自定义角色',
                'verbose_name_plural': '自定义角色',
                'db_table': 'custom_roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IPBlocklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP地址')),
                ('reason', models.CharField(blank=True, default='', max_length=200, verbose_name='原因')),
                ('blocked_until', models.DateTimeField(blank=True, null=True, verbose_name='封禁至')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'IP黑名单',
                'verbose_name_plural': 'IP黑名单',
                'db_table': 'ip_blocklist',
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User-Agent')),
                ('is_success', models.BooleanField(default=False, verbose_name='是否成功')),
                ('failure_reason', models.CharField(blank=True, default='', max_length=200, verbose_name='失败原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '登录尝试记录',
                'verbose_name_plural': '登录尝试记录',
                'db_table': 'login_attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TwoFactorSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=64, verbose_name='密钥')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='已启用')),
                ('backup_codes', models.JSONField(default=list, verbose_name='备用码')),
                ('enabled_at', models.DateTimeField(blank=True, null=True, verbose_name='启用时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '双因素认证',
                'verbose_name_plural': '双因素认证',
                'db_table': 'two_factor_secrets',
            },
        ),
        migrations.CreateModel(
            name='MemberGrowth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20, verbose_name='统计周期')),
                ('project_count', models.IntegerField(default=0, verbose_name='参与项目数')),
                ('task_count', models.IntegerField(default=0, verbose_name='完成任务数')),
                ('contribution_score', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='贡献得分')),
                ('skill_count', models.IntegerField(default=0, verbose_name='技能数')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '成员成长记录',
                'verbose_name_plural': '成员成长记录',
                'db_table': 'member_growth',
                'ordering': ['-period'],
                'unique_together': {('user', 'period')},
            },
        ),
        migrations.CreateModel(
            name='MemberSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='技能名称')),
                ('level', models.IntegerField(default=1, verbose_name='熟练度')),
                ('certified', models.BooleanField(default=False, verbose_name='已认证')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_matrix', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '成员技能矩阵',
                'verbose_name_plural': '成员技能矩阵',
                'db_table': 'users_member_skills',
                'ordering': ['-level', '-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='OAuthAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50, verbose_name='提供商')),
                ('provider_uid', models.CharField(max_length=200, verbose_name='第三方用户ID')),
                ('access_token', models.CharField(blank=True, default='', max_length=500, verbose_name='访问令牌')),
                ('refresh_token', models.CharField(blank=True, default='', max_length=500, verbose_name='刷新令牌')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_accounts', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '第三方账号绑定',
                'verbose_name_plural': '第三方账号绑定',
                'db_table': 'oauth_accounts',
                'ordering': ['-created_at'],
                'unique_together': {('provider', 'provider_uid')},
            },
        ),
        migrations.CreateModel(
            name='UserRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL, verbose_name='分配人')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='projects.project', verbose_name='项目')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='users.customrole', verbose_name='角色')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户角色分配',
                'verbose_name_plural': '用户角色分配',
                'db_table': 'user_role_assignments',
                'unique_together': {('user', 'role', 'project')},
            },
        ),
    ]
