# Generated by Django 6.0.6 on 2026-07-26 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_team_joined_at(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for user in User.objects.filter(team_joined_at__isnull=True).iterator():
        joined_date = user.date_joined.date() if user.date_joined else None
        if joined_date:
            User.objects.filter(pk=user.pk).update(team_joined_at=joined_date)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_primary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exit_reason',
            field=models.TextField(blank=True, default='', verbose_name='离队原因'),
        ),
        migrations.AddField(
            model_name='user',
            name='handover_notes',
            field=models.TextField(blank=True, default='', verbose_name='交接说明'),
        ),
        migrations.AddField(
            model_name='user',
            name='handover_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handover_from_users', to=settings.AUTH_USER_MODEL, verbose_name='交接人'),
        ),
        migrations.AddField(
            model_name='user',
            name='membership_status',
            field=models.CharField(choices=[('active', '在队'), ('on_leave', '暂离'), ('exited', '已离队'), ('external', '外部协作者')], db_index=True, default='active', max_length=20, verbose_name='成员状态'),
        ),
        migrations.AddField(
            model_name='user',
            name='team_joined_at',
            field=models.DateField(blank=True, null=True, verbose_name='加入团队日期'),
        ),
        migrations.AddField(
            model_name='user',
            name='team_left_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='离队时间'),
        ),
        migrations.RunPython(backfill_team_joined_at, migrations.RunPython.noop),
        migrations.AddField(
            model_name='userpreference',
            name='default_scope',
            field=models.CharField(choices=[('mine', '与我相关'), ('team', '团队全部')], default='mine', max_length=20, verbose_name='默认数据范围'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='favorite_routes',
            field=models.JSONField(blank=True, default=list, verbose_name='常用入口'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict, verbose_name='通知偏好'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='saved_filters',
            field=models.JSONField(blank=True, default=dict, verbose_name='保存的筛选条件'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='sidebar_order',
            field=models.JSONField(blank=True, default=list, verbose_name='侧边栏顺序'),
        ),
        migrations.CreateModel(
            name='UserLifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', '加入团队'), ('status_changed', '状态变更'), ('role_changed', '全局角色变更'), ('handover', '工作交接'), ('reactivated', '重新加入')], max_length=30, verbose_name='事件类型')),
                ('from_status', models.CharField(blank=True, default='', max_length=20, verbose_name='原状态')),
                ('to_status', models.CharField(blank=True, default='', max_length=20, verbose_name='新状态')),
                ('from_role', models.CharField(blank=True, default='', max_length=20, verbose_name='原角色')),
                ('to_role', models.CharField(blank=True, default='', max_length=20, verbose_name='新角色')),
                ('reason', models.TextField(blank=True, default='', verbose_name='原因')),
                ('handover_notes', models.TextField(blank=True, default='', verbose_name='交接说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
                ('handover_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_user_handovers', to=settings.AUTH_USER_MODEL, verbose_name='交接人')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_user_lifecycle_events', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_events', to=settings.AUTH_USER_MODEL, verbose_name='成员')),
            ],
            options={
                'verbose_name': '成员生命周期记录',
                'verbose_name_plural': '成员生命周期记录',
                'db_table': 'user_lifecycle_events',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
