# Generated by Django 5.0.6 on 2026-07-26 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_twofactorsecret'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='schedule_end',
            field=models.CharField(default='07:00', max_length=5, validators=[django.core.validators.RegexValidator(message='深色模式结束时间必须为 HH:MM 格式的有效时间', regex='^(?:[01]\\d|2[0-3]):[0-5]\\d$')], verbose_name='深色模式结束时间'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='schedule_start',
            field=models.CharField(default='19:00', max_length=5, validators=[django.core.validators.RegexValidator(message='深色模式开始时间必须为 HH:MM 格式的有效时间', regex='^(?:[01]\\d|2[0-3]):[0-5]\\d$')], verbose_name='深色模式开始时间'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='theme_mode',
            field=models.CharField(choices=[('light', '浅色'), ('dark', '深色'), ('system', '跟随系统'), ('schedule', '定时切换')], default='system', max_length=20, verbose_name='明暗模式'),
        ),
    ]
