# Generated by Django 5.0.6 on 2026-07-29 09:11

from django.db import migrations, models


def demote_extra_operating_teachers(apps, schema_editor):
    """Make legacy databases compatible while preserving the oldest operator."""
    User = apps.get_model('users', 'User')
    operating_teacher_ids = list(
        User.objects.filter(
            global_role='teacher',
            is_active=True,
        )
        .exclude(membership_status='exited')
        .order_by('date_joined', 'id')
        .values_list('id', flat=True)
    )
    if len(operating_teacher_ids) > 1:
        User.objects.filter(
            id__in=operating_teacher_ids[1:],
        ).update(global_role='member')


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0010_alter_user_global_role_teacher_label'),
    ]

    operations = [
        migrations.RunPython(
            demote_extra_operating_teachers,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('global_role', 'teacher'), ('is_active', True), models.Q(('membership_status', 'exited'), _negated=True)), fields=('global_role',), name='uniq_active_operating_teacher'),
        ),
    ]
