# Generated by Django 5.0.6 on 2026-07-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('login', '登录'), ('logout', '登出'), ('export', '导出'), ('import', '导入'), ('approve', '审批'), ('other', '其他')], default='other', max_length=20, verbose_name='操作类型')),
                ('module', models.CharField(blank=True, default='', max_length=50, verbose_name='操作模块')),
                ('object_type', models.CharField(blank=True, default='', max_length=100, verbose_name='对象类型')),
                ('object_id', models.CharField(blank=True, default='', max_length=50, verbose_name='对象ID')),
                ('description', models.TextField(blank=True, default='', verbose_name='操作描述')),
                ('request_method', models.CharField(blank=True, default='', max_length=10, verbose_name='请求方法')),
                ('request_path', models.CharField(blank=True, default='', max_length=500, verbose_name='请求路径')),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='请求IP')),
                ('request_data', models.JSONField(blank=True, null=True, verbose_name='请求参数')),
                ('response_status', models.IntegerField(blank=True, null=True, verbose_name='响应状态码')),
                ('is_success', models.BooleanField(default=True, verbose_name='是否成功')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'operation_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
