# Generated by Django 5.0.6
"""为 OperationLog 添加 user_agent 字段并扩展 operation_type 选项"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
    ]

    operations = [
        # 添加 user_agent 字段
        migrations.AddField(
            model_name='operationlog',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='User-Agent'),
        ),
        # 更新 operation_type 选项（增加 upload/download/reject/review/view_sensitive）
        migrations.AlterField(
            model_name='operationlog',
            name='operation_type',
            field=models.CharField(
                choices=[
                    ('create', '创建'),
                    ('update', '更新'),
                    ('delete', '删除'),
                    ('login', '登录'),
                    ('logout', '登出'),
                    ('export', '导出'),
                    ('import', '导入'),
                    ('upload', '上传'),
                    ('download', '下载'),
                    ('approve', '审批'),
                    ('reject', '驳回'),
                    ('review', '审核'),
                    ('view_sensitive', '查看敏感'),
                    ('other', '其他'),
                ],
                default='other',
                max_length=20,
                verbose_name='操作类型',
            ),
        ),
    ]
