# Generated by Django 5.0.6 on 2026-07-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensitiveAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='申请理由')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已驳回'), ('expired', '已过期')], default='pending', max_length=20, verbose_name='审批状态')),
                ('approval_comment', models.TextField(blank=True, default='', verbose_name='审批意见')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('access_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='访问有效期截止')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '敏感数据访问申请',
                'verbose_name_plural': '敏感数据访问申请',
                'db_table': 'sensitive_access_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SensitiveData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('personal_info', '个人信息'), ('financial_info', '财务信息'), ('contract', '合同文件'), ('certificate', '证书证件'), ('other', '其他')], default='other', max_length=20, verbose_name='数据类型')),
                ('title', models.CharField(max_length=200, verbose_name='数据标题')),
                ('encrypted_content', models.TextField(blank=True, default='', verbose_name='加密内容')),
                ('encrypted_file_path', models.CharField(blank=True, default='', max_length=500, verbose_name='加密文件路径')),
                ('is_encrypted', models.BooleanField(default=False, verbose_name='已加密')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '敏感数据',
                'verbose_name_plural': '敏感数据',
                'db_table': 'sensitive_data',
                'ordering': ['-created_at'],
            },
        ),
    ]
