# Generated by Django 5.0.6 on 2026-07-01 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_initial'),
        ('projects', '0002_initial'),
        ('sensitive', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensitiveaccessrequest',
            name='approval_opinion',
            field=models.TextField(blank=True, default='', verbose_name='审批意见'),
        ),
        migrations.AddField(
            model_name='sensitiveaccessrequest',
            name='expected_use_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='预计使用时间'),
        ),
        migrations.AddField(
            model_name='sensitiveaccessrequest',
            name='is_download',
            field=models.BooleanField(default=False, verbose_name='是否需要下载'),
        ),
        migrations.AddField(
            model_name='sensitiveaccessrequest',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensitive_access_requests', to='projects.project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='sensitiveaccessrequest',
            name='request_note',
            field=models.TextField(blank=True, default='', verbose_name='申请说明'),
        ),
        migrations.AddField(
            model_name='sensitiveaccessrequest',
            name='usage_scenario',
            field=models.TextField(blank=True, default='', verbose_name='使用场景'),
        ),
        migrations.AddField(
            model_name='sensitiveaccessrequest',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='首次查看时间'),
        ),
        migrations.AddField(
            model_name='sensitivedata',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='显示名称'),
        ),
        migrations.AddField(
            model_name='sensitivedata',
            name='file_attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensitive_data_attachments', to='files.fileasset', verbose_name='附件'),
        ),
        migrations.AddField(
            model_name='sensitivedata',
            name='key_version',
            field=models.IntegerField(default=1, verbose_name='密钥版本'),
        ),
        migrations.AlterField(
            model_name='sensitivedata',
            name='data_type',
            field=models.CharField(choices=[('id_card', '身份证号'), ('bank_account', '银行账号'), ('phone', '手机号'), ('address', '住址'), ('signature', '签名'), ('other', '其他')], default='other', max_length=20, verbose_name='数据类型'),
        ),
    ]
