# Generated by Django 5.0.6 on 2026-07-01 11:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='奖金总额')),
                ('other_income', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='其他收入')),
                ('used_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='已用金额')),
                ('pending_reimbursement', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='待报销金额')),
                ('status', models.CharField(choices=[('normal', '正常'), ('warning', '预警'), ('abnormal', '异常')], default='normal', max_length=20, verbose_name='经费状态')),
                ('period', models.CharField(blank=True, default='', max_length=20, verbose_name='统计周期')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '经费总表',
                'verbose_name_plural': '经费总表',
                'db_table': 'finance_budgets',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FinanceExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='支出标题')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金额')),
                ('expense_date', models.DateField(verbose_name='支出日期')),
                ('category', models.CharField(choices=[('material', '材料费'), ('equipment', '设备费'), ('printing', '打印费'), ('travel', '差旅费'), ('software', '软件费'), ('competition_fee', '比赛报名费'), ('promotion', '推广费'), ('labor', '劳务费'), ('other', '其他')], default='other', max_length=20, verbose_name='经费类别')),
                ('purpose', models.TextField(blank=True, default='', verbose_name='用途说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '经费明细',
                'verbose_name_plural': '经费明细',
                'db_table': 'finance_expenses',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinanceReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='finance/receipts/', verbose_name='票据图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '票据图片',
                'verbose_name_plural': '票据图片',
                'db_table': 'finance_receipts',
                'ordering': ['-created_at'],
            },
        ),
    ]
