# Generated by Django 5.0.6 on 2026-07-29 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def check_constraint(*, condition, name):
    """Keep this migration importable on both Django 5.0 and Django 6.x."""
    try:
        return models.CheckConstraint(condition=condition, name=name)
    except TypeError:
        return models.CheckConstraint(check=condition, name=name)


def migrate_legacy_finance_records(apps, schema_editor):
    FinanceExpense = apps.get_model('finance', 'FinanceExpense')
    FinanceIncome = apps.get_model('finance', 'FinanceIncome')
    FinancePayment = apps.get_model('finance', 'FinancePayment')

    for expense in FinanceExpense.objects.all().iterator():
        payee_id = expense.payee_id or expense.spender_id or expense.applied_by_id
        if payee_id and expense.payee_id != payee_id:
            FinanceExpense.objects.filter(pk=expense.pk).update(payee_id=payee_id)
        if expense.reimbursement_status == 'paid':
            FinancePayment.objects.get_or_create(
                expense_id=expense.pk,
                is_legacy=True,
                defaults={
                    'recipient_id': payee_id,
                    'amount': expense.amount,
                    'status': 'completed',
                    'payment_method': expense.payment_method or '历史台账迁移',
                    'payment_reference': expense.payment_reference or '',
                    'paid_by_id': expense.paid_by_id,
                    'paid_at': expense.paid_at or expense.updated_at,
                },
            )

    for income in FinanceIncome.objects.filter(stage='received').iterator():
        FinanceIncome.objects.filter(pk=income.pk).update(
            confirmed_at=income.created_at,
            received_at=income.created_at,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_competitionevent_competition_entry_name_and_more'),
        ('finance', '0006_financebudget_planned_amount'),
        ('projects', '0009_project_teams_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financeexpense',
            name='competition_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_expenses', to='competitions.competition', verbose_name='参赛条目'),
        ),
        migrations.AddField(
            model_name='financeexpense',
            name='payee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_reimbursements', to=settings.AUTH_USER_MODEL, verbose_name='实际收款人'),
        ),
        migrations.AddField(
            model_name='financeincome',
            name='competition_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_incomes', to='competitions.competition', verbose_name='参赛条目'),
        ),
        migrations.AddField(
            model_name='financeincome',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='确认应收时间'),
        ),
        migrations.AddField(
            model_name='financeincome',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='到账时间'),
        ),
        migrations.AddField(
            model_name='financeincome',
            name='stage',
            field=models.CharField(choices=[('expected', '预计收入'), ('confirmed', '已确认应收'), ('received', '已到账')], db_index=True, default='received', max_length=20, verbose_name='收入阶段'),
        ),
        migrations.AddField(
            model_name='financereceipt',
            name='attachment_type',
            field=models.CharField(choices=[('invoice', '发票'), ('original_receipt', '原始票据'), ('payment_proof', '付款回单'), ('income_proof', '奖金/收入到账凭证'), ('transfer_proof', '内部转账凭证'), ('other', '其他')], default='invoice', max_length=30, verbose_name='附件类型'),
        ),
        migrations.AddField(
            model_name='financereceipt',
            name='income',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='finance.financeincome', verbose_name='关联收入'),
        ),
        migrations.AlterField(
            model_name='financeexpense',
            name='reimbursement_status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待报销审核'), ('approved', '审核通过·待打款'), ('partial_paid', '部分支付'), ('payment_exception', '付款异常'), ('rejected', '已驳回'), ('paid', '已打款·报销完成'), ('not_required', '无需报销')], db_index=True, default='draft', max_length=20, verbose_name='报销状态'),
        ),
        migrations.AlterField(
            model_name='financereceipt',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='finance.financeexpense', verbose_name='关联经费明细'),
        ),
        migrations.CreateModel(
            name='FinanceExpenseAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='分摊金额')),
                ('note', models.TextField(blank=True, default='', verbose_name='分摊说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('competition_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_allocations', to='competitions.competition', verbose_name='参赛条目')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.financeexpense', verbose_name='支出')),
            ],
            options={
                'verbose_name': '支出分摊',
                'verbose_name_plural': '支出分摊',
                'db_table': 'finance_expense_allocations',
                'ordering': ['competition_entry_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FinanceIncomeAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='分摊金额')),
                ('note', models.TextField(blank=True, default='', verbose_name='分摊说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('competition_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='income_allocations', to='competitions.competition', verbose_name='参赛条目')),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.financeincome', verbose_name='收入')),
            ],
            options={
                'verbose_name': '收入分摊',
                'verbose_name_plural': '收入分摊',
                'db_table': 'finance_income_allocations',
                'ordering': ['competition_entry_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FinanceInternalTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_label', models.CharField(blank=True, default='', max_length=200, verbose_name='外部来源')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='转移金额')),
                ('status', models.CharField(choices=[('pending_proof', '待补转账凭证'), ('completed', '转移完成'), ('failed', '转移异常')], db_index=True, default='pending_proof', max_length=20, verbose_name='转移状态')),
                ('payment_method', models.CharField(max_length=50, verbose_name='转账方式')),
                ('payment_reference', models.CharField(blank=True, default='', max_length=100, verbose_name='转账流水号')),
                ('transferred_at', models.DateTimeField(blank=True, null=True, verbose_name='转账时间')),
                ('failure_reason', models.TextField(blank=True, default='', verbose_name='异常原因')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('competition_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_internal_transfers', to='competitions.competition', verbose_name='参赛条目')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_transfers_sent', to=settings.AUTH_USER_MODEL, verbose_name='转出经办人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_internal_transfers', to='projects.project', verbose_name='所属项目')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_finance_transfers', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_transfers_received', to=settings.AUTH_USER_MODEL, verbose_name='转入经办人')),
            ],
            options={
                'verbose_name': '项目内部资金转移',
                'verbose_name_plural': '项目内部资金转移',
                'db_table': 'finance_internal_transfers',
                'ordering': ['-transferred_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='financereceipt',
            name='internal_transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='finance.financeinternaltransfer', verbose_name='关联内部转移'),
        ),
        migrations.CreateModel(
            name='FinancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='付款金额')),
                ('status', models.CharField(choices=[('pending_proof', '待补付款凭证'), ('completed', '已付款'), ('failed', '付款异常'), ('reversed', '已冲正')], db_index=True, default='pending_proof', max_length=20, verbose_name='付款状态')),
                ('payment_method', models.CharField(max_length=50, verbose_name='付款方式')),
                ('payment_reference', models.CharField(blank=True, default='', max_length=100, verbose_name='付款流水号')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='付款时间')),
                ('failure_reason', models.TextField(blank=True, default='', verbose_name='付款异常原因')),
                ('is_legacy', models.BooleanField(default=False, verbose_name='历史迁移付款')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.financeexpense', verbose_name='报销申请')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_payments_made', to=settings.AUTH_USER_MODEL, verbose_name='付款登记人')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_payments_received', to=settings.AUTH_USER_MODEL, verbose_name='收款人')),
            ],
            options={
                'verbose_name': '报销付款',
                'verbose_name_plural': '报销付款',
                'db_table': 'finance_payments',
                'ordering': ['-paid_at', '-created_at'],
            },
        ),
        migrations.RunPython(
            migrate_legacy_finance_records,
            migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='FinanceLedgerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=50, verbose_name='事件类型')),
                ('from_status', models.CharField(blank=True, default='', max_length=30, verbose_name='原状态')),
                ('to_status', models.CharField(blank=True, default='', max_length=30, verbose_name='新状态')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='相关金额')),
                ('description', models.TextField(blank=True, default='', verbose_name='事件说明')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='发生时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_ledger_events', to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_events', to='finance.financeexpense')),
                ('income', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_events', to='finance.financeincome')),
                ('internal_transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_events', to='finance.financeinternaltransfer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_ledger_events', to='projects.project', verbose_name='所属项目')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_events', to='finance.financepayment')),
            ],
            options={
                'verbose_name': '资金时间线事件',
                'verbose_name_plural': '资金时间线事件',
                'db_table': 'finance_ledger_events',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='financereceipt',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='finance.financepayment', verbose_name='关联付款'),
        ),
        migrations.AddConstraint(
            model_name='financereceipt',
            constraint=check_constraint(condition=models.Q(models.Q(('expense__isnull', False), ('income__isnull', True), ('internal_transfer__isnull', True), ('payment__isnull', True)), models.Q(('expense__isnull', True), ('income__isnull', False), ('internal_transfer__isnull', True), ('payment__isnull', True)), models.Q(('expense__isnull', True), ('income__isnull', True), ('internal_transfer__isnull', True), ('payment__isnull', False)), models.Q(('expense__isnull', True), ('income__isnull', True), ('internal_transfer__isnull', False), ('payment__isnull', True)), _connector='OR'), name='finance_receipt_exactly_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='financeexpenseallocation',
            constraint=models.UniqueConstraint(fields=('expense', 'competition_entry'), name='uniq_expense_competition_allocation'),
        ),
        migrations.AddConstraint(
            model_name='financeexpenseallocation',
            constraint=check_constraint(condition=models.Q(('amount__gt', 0)), name='finance_expense_allocation_amount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='financeincomeallocation',
            constraint=models.UniqueConstraint(fields=('income', 'competition_entry'), name='uniq_income_competition_allocation'),
        ),
        migrations.AddConstraint(
            model_name='financeincomeallocation',
            constraint=check_constraint(condition=models.Q(('amount__gt', 0)), name='finance_income_allocation_amount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='financeinternaltransfer',
            constraint=check_constraint(condition=models.Q(('amount__gt', 0)), name='finance_internal_transfer_amount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='financepayment',
            constraint=check_constraint(condition=models.Q(('amount__gt', 0)), name='finance_payment_amount_gt_zero'),
        ),
    ]
