# Generated by Django 5.0.6 on 2026-07-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntellectualPropertyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='成果名称')),
                ('application_code', models.CharField(max_length=50, unique=True, verbose_name='内部编号')),
                ('ip_type', models.CharField(choices=[('software_copyright', '软件著作权'), ('invention_patent', '发明专利'), ('utility_model', '实用新型专利'), ('design_patent', '外观设计专利'), ('paper', '论文成果'), ('other', '其他')], default='software_copyright', max_length=30, verbose_name='成果类型')),
                ('status', models.CharField(choices=[('draft', '准备中'), ('writing', '材料撰写中'), ('leader_review', '项目负责人审核中'), ('teacher_confirm', '老师确认中'), ('research_office_review', '科研处审核中'), ('returned', '科研处退回修改'), ('modifying', '修改中'), ('resubmitted', '已重新提交'), ('accepted', '已受理'), ('authorized', '已授权/已登记'), ('archived', '已归档'), ('paused', '暂停申请'), ('terminated', '终止申请'), ('deferred', '转为后续申请')], default='draft', max_length=30, verbose_name='当前状态')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('submit_date', models.DateField(blank=True, null=True, verbose_name='提交日期')),
                ('accepted_date', models.DateField(blank=True, null=True, verbose_name='受理日期')),
                ('authorized_date', models.DateField(blank=True, null=True, verbose_name='授权/登记日期')),
                ('return_count', models.IntegerField(default=0, verbose_name='退回次数')),
                ('current_problem', models.TextField(blank=True, default='', verbose_name='当前问题')),
                ('intro', models.TextField(blank=True, default='', verbose_name='成果简介')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '知识产权申请',
                'verbose_name_plural': '知识产权申请',
                'db_table': 'ip_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IPApplicationContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('main_writer', '主导撰写人'), ('co_writer', '协作撰写人'), ('code_provider', '代码提供人'), ('document_writer', '文档撰写人'), ('drawing_provider', '图纸提供人'), ('tester', '测试人'), ('executor', '申请执行人'), ('material_manager', '材料整理人'), ('reviewer', '审核人')], max_length=30, verbose_name='贡献角色')),
                ('contribution_description', models.TextField(blank=True, default='', verbose_name='贡献说明')),
                ('responsibility_description', models.TextField(blank=True, default='', verbose_name='责任说明')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='是否确认')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '知识产权责任分工',
                'verbose_name_plural': '知识产权责任分工',
                'db_table': 'ip_contributors',
            },
        ),
        migrations.CreateModel(
            name='IPMaterialVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('application_form', '申请表'), ('manual', '软件说明书'), ('source_code', '源代码文档'), ('screenshot', '软件截图'), ('disclosure', '专利交底书'), ('specification', '专利说明书'), ('claims', '权利要求书'), ('abstract', '摘要'), ('drawing', '附图'), ('feedback', '科研处反馈截图'), ('system_screenshot', '申请系统截图'), ('acceptance_notice', '受理通知书'), ('certificate', '授权证书'), ('archive', '归档材料'), ('other', '其他')], default='other', max_length=30, verbose_name='材料类型')),
                ('version', models.CharField(default='v1', max_length=20, verbose_name='版本号')),
                ('change_note', models.TextField(blank=True, default='', verbose_name='修改说明')),
                ('is_final', models.BooleanField(default=False, verbose_name='是否最终版')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '材料版本',
                'verbose_name_plural': '材料版本',
                'db_table': 'ip_material_versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IPObjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objection_type', models.CharField(choices=[('writing_credit', '撰写贡献异议'), ('execution_credit', '申请执行贡献异议'), ('return_responsibility', '退回责任异议'), ('ranking', '成果排序异议'), ('material_credit', '材料撰写异议'), ('other', '其他')], default='other', max_length=30, verbose_name='异议类型')),
                ('content', models.TextField(verbose_name='异议内容')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('leader_reviewed', '负责人已初审'), ('teacher_confirmed', '老师已确认'), ('resolved', '已解决'), ('rejected', '已驳回')], default='pending', max_length=30, verbose_name='处理状态')),
                ('leader_opinion', models.TextField(blank=True, default='', verbose_name='负责人意见')),
                ('leader_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='负责人审核时间')),
                ('teacher_opinion', models.TextField(blank=True, default='', verbose_name='老师意见')),
                ('teacher_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='老师确认时间')),
                ('final_result', models.TextField(blank=True, default='', verbose_name='最终结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '知识产权异议',
                'verbose_name_plural': '知识产权异议',
                'db_table': 'ip_objections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IPReturnRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_time', models.DateTimeField(verbose_name='退回时间')),
                ('return_source', models.CharField(choices=[('research_office', '科研处'), ('school_system', '学校系统'), ('agency', '代理机构'), ('patent_platform', '专利平台'), ('other', '其他')], default='research_office', max_length=30, verbose_name='退回来源')),
                ('return_reason', models.TextField(verbose_name='退回原因')),
                ('responsibility_type', models.CharField(choices=[('writing_problem', '撰写质量问题'), ('material_problem', '材料完整性问题'), ('submit_problem', '提交流程问题'), ('review_problem', '审核问题'), ('system_problem', '系统问题'), ('unattributable', '无法归属'), ('other', '其他')], default='other', max_length=30, verbose_name='责任类型')),
                ('modify_deadline', models.DateTimeField(blank=True, null=True, verbose_name='修改截止时间')),
                ('modify_description', models.TextField(blank=True, default='', verbose_name='修改说明')),
                ('result', models.CharField(choices=[('pending', '待修改'), ('modified', '已修改'), ('resubmitted', '已重新提交'), ('accepted', '已通过'), ('rejected', '未通过')], default='pending', max_length=20, verbose_name='处理结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '退回修改记录',
                'verbose_name_plural': '退回修改记录',
                'db_table': 'ip_return_records',
                'ordering': ['-return_time'],
            },
        ),
    ]
