# Generated by Django 5.0.6 on 2026-07-01 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0003_initial'),
        ('intellectual_property', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='intellectualpropertyapplication',
            name='applicant_executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_executing', to=settings.AUTH_USER_MODEL, verbose_name='申请执行人'),
        ),
        migrations.AddField(
            model_name='intellectualpropertyapplication',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_applications_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='intellectualpropertyapplication',
            name='final_certificate_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_certificates', to='files.fileasset', verbose_name='最终证书文件'),
        ),
        migrations.AddField(
            model_name='intellectualpropertyapplication',
            name='main_writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_main_writing', to=settings.AUTH_USER_MODEL, verbose_name='主导撰写人'),
        ),
        migrations.AddField(
            model_name='intellectualpropertyapplication',
            name='material_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_material_managing', to=settings.AUTH_USER_MODEL, verbose_name='材料整理人'),
        ),
        migrations.AddField(
            model_name='intellectualpropertyapplication',
            name='project_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_reviewing', to=settings.AUTH_USER_MODEL, verbose_name='项目负责人审核人'),
        ),
        migrations.AddField(
            model_name='intellectualpropertyapplication',
            name='related_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_applications', to='projects.project', verbose_name='关联项目'),
        ),
        migrations.AddField(
            model_name='intellectualpropertyapplication',
            name='teacher_confirmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_confirming', to=settings.AUTH_USER_MODEL, verbose_name='老师确认人'),
        ),
        migrations.AddField(
            model_name='ipapplicationcontributor',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='intellectual_property.intellectualpropertyapplication', verbose_name='所属申请'),
        ),
        migrations.AddField(
            model_name='ipapplicationcontributor',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_confirmations', to=settings.AUTH_USER_MODEL, verbose_name='确认人'),
        ),
        migrations.AddField(
            model_name='ipapplicationcontributor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_contributions', to=settings.AUTH_USER_MODEL, verbose_name='成员'),
        ),
        migrations.AddField(
            model_name='ipmaterialversion',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_versions', to='intellectual_property.intellectualpropertyapplication', verbose_name='所属申请'),
        ),
        migrations.AddField(
            model_name='ipmaterialversion',
            name='file_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_materials', to='files.fileasset', verbose_name='关联文件'),
        ),
        migrations.AddField(
            model_name='ipmaterialversion',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_materials_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='上传人'),
        ),
        migrations.AddField(
            model_name='ipobjection',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objections', to='intellectual_property.intellectualpropertyapplication', verbose_name='所属申请'),
        ),
        migrations.AddField(
            model_name='ipobjection',
            name='leader_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_objection_leader_reviews', to=settings.AUTH_USER_MODEL, verbose_name='负责人审核人'),
        ),
        migrations.AddField(
            model_name='ipobjection',
            name='objector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_objections', to=settings.AUTH_USER_MODEL, verbose_name='提出人'),
        ),
        migrations.AddField(
            model_name='ipobjection',
            name='proof_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_objection_proofs', to='files.fileasset', verbose_name='证明文件'),
        ),
        migrations.AddField(
            model_name='ipobjection',
            name='teacher_confirmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_objection_teacher_confirms', to=settings.AUTH_USER_MODEL, verbose_name='老师确认人'),
        ),
        migrations.AddField(
            model_name='ipreturnrecord',
            name='actual_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_actual_modified_returns', to=settings.AUTH_USER_MODEL, verbose_name='实际修改人'),
        ),
        migrations.AddField(
            model_name='ipreturnrecord',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_records', to='intellectual_property.intellectualpropertyapplication', verbose_name='所属申请'),
        ),
        migrations.AddField(
            model_name='ipreturnrecord',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_assigned_returns', to=settings.AUTH_USER_MODEL, verbose_name='指派人'),
        ),
        migrations.AddField(
            model_name='ipreturnrecord',
            name='proof_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_return_proofs', to='files.fileasset', verbose_name='证明文件'),
        ),
        migrations.AddField(
            model_name='ipreturnrecord',
            name='responsible_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_responsible_returns', to=settings.AUTH_USER_MODEL, verbose_name='责任人'),
        ),
        migrations.AddField(
            model_name='ipmaterialversion',
            name='related_return_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='intellectual_property.ipreturnrecord', verbose_name='关联退回记录'),
        ),
        migrations.AlterUniqueTogether(
            name='ipapplicationcontributor',
            unique_together={('application', 'user', 'role')},
        ),
    ]
