# Generated by Django 5.0.6 on 2026-07-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='任务标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='任务描述')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
                ('status', models.CharField(choices=[('todo', '待办'), ('doing', '进行中'), ('pending_review', '待审核'), ('done', '已完成'), ('overdue', '已逾期'), ('paused', '暂停'), ('cancelled', '已取消'), ('need_help', '需要帮助')], default='todo', max_length=20, verbose_name='任务状态')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('overdue_reminded', models.BooleanField(default=False, verbose_name='已逾期提醒')),
                ('delay_reason', models.TextField(blank=True, default='', verbose_name='延期原因')),
                ('attachments', models.TextField(blank=True, default='', verbose_name='附件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'db_table': 'tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('todo', '待办'), ('doing', '进行中'), ('pending_review', '待审核'), ('done', '已完成'), ('overdue', '已逾期'), ('paused', '暂停'), ('cancelled', '已取消'), ('need_help', '需要帮助')], default='', max_length=20, verbose_name='原状态')),
                ('to_status', models.CharField(choices=[('todo', '待办'), ('doing', '进行中'), ('pending_review', '待审核'), ('done', '已完成'), ('overdue', '已逾期'), ('paused', '暂停'), ('cancelled', '已取消'), ('need_help', '需要帮助')], max_length=20, verbose_name='目标状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '任务日志',
                'verbose_name_plural': '任务日志',
                'db_table': 'task_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
