# Generated by Django 5.0.6 on 2026-07-29 06:08

import django.core.validators
import django
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


CHECK_CONDITION_ARG = (
    'condition'
    if django.VERSION >= (5, 1)
    else 'check'
)


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_competitionevent_competition_entry_name_and_more'),
        ('tasks', '0007_task_completion_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='competition_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_items', to='competitions.competition', verbose_name='比赛参赛队'),
        ),
        migrations.AddField(
            model_name='task',
            name='reference_note',
            field=models.TextField(blank=True, default='', verbose_name='参考说明'),
        ),
        migrations.CreateModel(
            name='CompetitionWorkloadAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='版本')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('superseded', '已被新版本替代')], db_index=True, default='draft', max_length=20, verbose_name='状态')),
                ('decision_note', models.TextField(blank=True, default='', verbose_name='评议说明')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('is_current', models.BooleanField(default=False, verbose_name='是否为当前发布版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_assessments', to='competitions.competition', verbose_name='比赛参赛队')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_competition_workloads', to=settings.AUTH_USER_MODEL, verbose_name='评议人')),
            ],
            options={
                'verbose_name': '比赛工作量评议',
                'verbose_name_plural': '比赛工作量评议',
                'db_table': 'competition_workload_assessments',
                'ordering': ['-version', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionWorkloadAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='贡献比例')),
                ('rationale', models.TextField(blank=True, default='', verbose_name='评议依据')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competition_workload_allocations', to=settings.AUTH_USER_MODEL, verbose_name='成员')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='tasks.competitionworkloadassessment', verbose_name='工作量评议')),
            ],
            options={
                'verbose_name': '比赛工作量分配',
                'verbose_name_plural': '比赛工作量分配',
                'db_table': 'competition_workload_allocations',
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionWorkloadObjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='异议理由')),
                ('status', models.CharField(choices=[('open', '待处理'), ('resolved', '已采纳处理'), ('rejected', '未采纳')], db_index=True, default='open', max_length=20, verbose_name='状态')),
                ('response', models.TextField(blank=True, default='', verbose_name='处理回复')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objections', to='tasks.competitionworkloadallocation', verbose_name='工作量分配')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competition_workload_objections', to=settings.AUTH_USER_MODEL, verbose_name='提出人')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_competition_workload_objections', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
            ],
            options={
                'verbose_name': '比赛工作量异议',
                'verbose_name_plural': '比赛工作量异议',
                'db_table': 'competition_workload_objections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='competitionworkloadassessment',
            constraint=models.UniqueConstraint(fields=('competition', 'version'), name='uniq_comp_workload_assessment_version'),
        ),
        migrations.AddConstraint(
            model_name='competitionworkloadassessment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('competition',), name='uniq_current_comp_workload_assessment'),
        ),
        migrations.AddConstraint(
            model_name='competitionworkloadallocation',
            constraint=models.UniqueConstraint(fields=('assessment', 'user'), name='uniq_comp_workload_allocation_user'),
        ),
        migrations.AddConstraint(
            model_name='competitionworkloadallocation',
            constraint=models.CheckConstraint(
                name='comp_workload_percentage_0_100',
                **{
                    CHECK_CONDITION_ARG: models.Q(
                        ('percentage__gte', 0),
                        ('percentage__lte', 100),
                    ),
                },
            ),
        ),
        migrations.AddConstraint(
            model_name='competitionworkloadobjection',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('allocation', 'raised_by'), name='uniq_open_comp_workload_objection'),
        ),
    ]
