# Generated by Django 5.0.6 on 2026-07-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='比赛名称')),
                ('comp_type', models.CharField(blank=True, default='', max_length=100, verbose_name='比赛类型')),
                ('level', models.CharField(choices=[('school', '校赛'), ('city', '市赛'), ('province', '省赛'), ('national', '国赛')], default='school', max_length=20, verbose_name='比赛级别')),
                ('organizer', models.CharField(blank=True, default='', max_length=200, verbose_name='主办单位')),
                ('register_date', models.DateField(blank=True, null=True, verbose_name='报名日期')),
                ('material_deadline', models.DateField(blank=True, null=True, verbose_name='材料截止日期')),
                ('review_date', models.DateField(blank=True, null=True, verbose_name='网评日期')),
                ('defense_date', models.DateField(blank=True, null=True, verbose_name='答辩日期')),
                ('school_date', models.DateField(blank=True, null=True, verbose_name='校赛日期')),
                ('city_date', models.DateField(blank=True, null=True, verbose_name='市赛日期')),
                ('province_date', models.DateField(blank=True, null=True, verbose_name='省赛日期')),
                ('national_date', models.DateField(blank=True, null=True, verbose_name='国赛日期')),
                ('result_date', models.DateField(blank=True, null=True, verbose_name='结果公布日期')),
                ('status', models.CharField(choices=[('preparing', '准备中'), ('ongoing', '进行中'), ('completed', '已结束')], default='preparing', max_length=20, verbose_name='比赛状态')),
                ('is_promoted', models.BooleanField(default=False, verbose_name='是否晋级')),
                ('is_awarded', models.BooleanField(default=False, verbose_name='是否获奖')),
                ('award_level', models.CharField(blank=True, default='', max_length=50, verbose_name='获奖等级')),
                ('not_promoted_reason', models.TextField(blank=True, default='', verbose_name='未晋级原因')),
                ('improvement_suggestion', models.TextField(blank=True, default='', verbose_name='改进建议')),
                ('review_summary', models.TextField(blank=True, default='', verbose_name='评审总结')),
                ('current_stage', models.CharField(blank=True, default='', max_length=100, verbose_name='当前阶段')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '比赛',
                'verbose_name_plural': '比赛',
                'db_table': 'competitions',
                'ordering': ['-created_at'],
            },
        ),
    ]
