# Generated by Django 5.0.6 on 2026-07-07 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_name', models.CharField(max_length=200, verbose_name='奖项名称')),
                ('award_level', models.CharField(blank=True, default='', max_length=50, verbose_name='获奖等级')),
                ('award_date', models.DateField(blank=True, null=True, verbose_name='获奖日期')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='competitions.competition', verbose_name='关联比赛')),
                ('recipients', models.ManyToManyField(blank=True, related_name='competition_awards', to=settings.AUTH_USER_MODEL, verbose_name='获奖人')),
            ],
            options={
                'verbose_name': '比赛获奖记录',
                'verbose_name_plural': '比赛获奖记录',
                'db_table': 'competition_awards',
                'ordering': ['-award_date', '-created_at'],
            },
        ),
    ]
