# Generated by Django 5.0.6 on 2026-07-29 05:25

import django.db.models.deletion
from django.db import migrations, models


def create_competition_events(apps, schema_editor):
    Competition = apps.get_model('competitions', 'Competition')
    CompetitionEvent = apps.get_model('competitions', 'CompetitionEvent')
    events_by_key = {}

    competitions = Competition.objects.select_related('project').order_by('id')
    for competition in competitions.iterator():
        organization_id = next((
            parent_id or team_id
            for team_id, parent_id in competition.project.teams.values_list(
                'id',
                'parent_id',
            )
        ), None)
        edition_date = next((
            value for value in (
                competition.register_date,
                competition.school_date,
                competition.city_date,
                competition.province_date,
                competition.national_date,
                competition.result_date,
            )
            if value
        ), None)
        edition = str(
            edition_date.year
            if edition_date
            else competition.created_at.year
        )
        key = (
            organization_id,
            (competition.name or '').strip().casefold(),
            (competition.organizer or '').strip().casefold(),
            edition,
        )
        event = events_by_key.get(key)
        if event is None:
            event = CompetitionEvent.objects.create(
                organization_id=organization_id,
                name=(competition.name or '').strip(),
                edition=edition,
                organizer=(competition.organizer or '').strip(),
            )
            events_by_key[key] = event
        competition.event_id = event.id
        competition.entry_name = competition.project.name
        competition.save(update_fields=['event', 'entry_name'])


def remove_competition_events(apps, schema_editor):
    Competition = apps.get_model('competitions', 'Competition')
    CompetitionEvent = apps.get_model('competitions', 'CompetitionEvent')
    Competition.objects.update(event=None, entry_name='')
    CompetitionEvent.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_team_hierarchy_and_co_lead'),
        ('competitions', '0004_competition_participant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='比赛名称')),
                ('edition', models.CharField(blank=True, default='', max_length=50, verbose_name='届次 / 年份')),
                ('organizer', models.CharField(blank=True, default='', max_length=200, verbose_name='主办单位')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competition_events', to='common.team', verbose_name='所属总团队')),
            ],
            options={
                'verbose_name': '比赛届次',
                'verbose_name_plural': '比赛届次',
                'db_table': 'competition_events',
                'ordering': ['-edition', 'name', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='competition',
            name='entry_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='参赛队 / 报名队名称'),
        ),
        migrations.AddField(
            model_name='competition',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='competitions.competitionevent', verbose_name='比赛届次'),
        ),
        migrations.RunPython(
            create_competition_events,
            remove_competition_events,
        ),
        migrations.AddConstraint(
            model_name='competitionevent',
            constraint=models.UniqueConstraint(
                condition=models.Q(('organization__isnull', False)),
                fields=('organization', 'name', 'edition', 'organizer'),
                name='uniq_comp_event_org_name_edition_org',
            ),
        ),
    ]
