# Generated by Django 5.0.6 on 2026-07-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_type', models.CharField(choices=[('task_complete', '任务完成'), ('project_lead', '项目负责人'), ('competition', '比赛参与'), ('finance_manage', '经费管理'), ('file_upload', '文件上传'), ('ip_writing', '软著/专利撰写贡献'), ('ip_execution', '软著/专利申请执行贡献'), ('ip_return_fix', '软著/专利退回修改贡献'), ('ip_archive', '成果归档贡献'), ('ip_material', '材料整理贡献'), ('other', '其他')], default='other', max_length=20, verbose_name='贡献类型')),
                ('description', models.TextField(blank=True, default='', verbose_name='贡献描述')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='贡献分值')),
                ('related_object_id', models.IntegerField(blank=True, null=True, verbose_name='关联对象ID')),
                ('period', models.CharField(blank=True, default='', max_length=20, verbose_name='统计周期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '贡献记录',
                'verbose_name_plural': '贡献记录',
                'db_table': 'contributions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20, verbose_name='统计周期')),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总贡献分值')),
                ('rank', models.IntegerField(default=0, verbose_name='排名')),
                ('task_completed_count', models.IntegerField(default=0, verbose_name='任务完成数')),
                ('project_count', models.IntegerField(default=0, verbose_name='参与项目数')),
                ('competition_count', models.IntegerField(default=0, verbose_name='比赛参与数')),
                ('is_published', models.BooleanField(default=False, verbose_name='已公示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '成员排名',
                'verbose_name_plural': '成员排名',
                'db_table': 'member_rankings',
                'ordering': ['period', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='RankingObjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='异议内容')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='处理状态')),
                ('reply', models.TextField(blank=True, default='', verbose_name='处理回复')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '排名异议',
                'verbose_name_plural': '排名异议',
                'db_table': 'ranking_objections',
                'ordering': ['-created_at'],
            },
        ),
    ]
