# Generated by Django 5.0.6 on 2026-07-01 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0003_initial'),
        ('files', '0003_initial'),
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='memberranking',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contribution',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='贡献内容'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='filled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filled_contributions', to=settings.AUTH_USER_MODEL, verbose_name='填写人'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='proof_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribution_proofs', to='files.fileasset', verbose_name='证明材料'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='review_opinion',
            field=models.TextField(blank=True, default='', verbose_name='审核意见'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_contributions', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='审核状态'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='权重'),
        ),
        migrations.AddField(
            model_name='memberranking',
            name='ip_contribution_count',
            field=models.IntegerField(default=0, verbose_name='IP贡献数'),
        ),
        migrations.AddField(
            model_name='memberranking',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='是否公开'),
        ),
        migrations.AddField(
            model_name='memberranking',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='projects.project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='memberranking',
            name='status',
            field=models.CharField(choices=[('draft', '草案'), ('confirmed', '已确认')], default='draft', max_length=20, verbose_name='排名状态'),
        ),
        migrations.AddField(
            model_name='rankingobjection',
            name='final_result',
            field=models.TextField(blank=True, default='', verbose_name='最终结果'),
        ),
        migrations.AddField(
            model_name='rankingobjection',
            name='leader_opinion',
            field=models.TextField(blank=True, default='', verbose_name='负责人初审意见'),
        ),
        migrations.AddField(
            model_name='rankingobjection',
            name='leader_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='负责人审核时间'),
        ),
        migrations.AddField(
            model_name='rankingobjection',
            name='leader_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ranking_objection_leader_reviews', to=settings.AUTH_USER_MODEL, verbose_name='负责人审核人'),
        ),
        migrations.AddField(
            model_name='rankingobjection',
            name='teacher_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='老师确认时间'),
        ),
        migrations.AddField(
            model_name='rankingobjection',
            name='teacher_confirmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ranking_objection_teacher_confirms', to=settings.AUTH_USER_MODEL, verbose_name='老师确认人'),
        ),
        migrations.AddField(
            model_name='rankingobjection',
            name='teacher_opinion',
            field=models.TextField(blank=True, default='', verbose_name='老师意见'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='contribution_type',
            field=models.CharField(choices=[('task_complete', '任务完成'), ('project_lead', '项目负责人'), ('competition', '比赛参与'), ('finance_manage', '经费管理'), ('file_upload', '文件上传'), ('ip_writing', '软著/专利撰写贡献'), ('ip_execution', '软著/专利申请执行贡献'), ('ip_return_fix', '软著/专利退回修改贡献'), ('ip_archive', '成果归档贡献'), ('ip_material', '材料整理贡献'), ('project_leader', '项目负责人统筹'), ('core', '核心成员'), ('long_term', '长期贡献'), ('stage_task', '阶段性任务'), ('resource', '资源贡献'), ('temporary_help', '临时协助'), ('nominal', '挂名贡献'), ('exited_contribution', '已退出成员贡献'), ('other', '其他')], default='other', max_length=30, verbose_name='贡献类型'),
        ),
        migrations.AlterField(
            model_name='rankingobjection',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('leader_reviewed', '负责人已初审'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='处理状态'),
        ),
        migrations.AlterUniqueTogether(
            name='memberranking',
            unique_together={('project', 'user', 'period')},
        ),
    ]
