# Generated by Django 5.0.6 on 2026-07-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlexibleWorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='时段开始')),
                ('period_end', models.DateField(verbose_name='时段结束')),
                ('work_hours', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='可用工时')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='工时明细')),
                ('can_offline', models.BooleanField(default=False, verbose_name='可以线下')),
                ('can_urgent', models.BooleanField(default=False, verbose_name='可以紧急任务')),
                ('is_saturated', models.BooleanField(default=False, verbose_name='已饱和')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('filled_at', models.DateTimeField(auto_now_add=True, verbose_name='填写时间')),
            ],
            options={
                'verbose_name': '灵活工时',
                'verbose_name_plural': '灵活工时',
                'db_table': 'flexible_work_schedules',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='MemberSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.IntegerField(default=1, verbose_name='熟练度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '成员技能',
                'verbose_name_plural': '成员技能',
                'db_table': 'member_skills',
            },
        ),
        migrations.CreateModel(
            name='SkillTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='技能名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '技能标签',
                'verbose_name_plural': '技能标签',
                'db_table': 'skill_tags',
                'ordering': ['name'],
            },
        ),
    ]
