# Generated by Django 5.0.6 on 2026-07-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='集成名称')),
                ('provider', models.CharField(choices=[('feishu', '飞书'), ('wecom', '企业微信'), ('qqbot', 'QQ机器人'), ('webhook', '通用Webhook'), ('email', '邮件')], default='webhook', max_length=20, verbose_name='服务提供商')),
                ('webhook_url', models.URLField(blank=True, default='', verbose_name='Webhook地址')),
                ('app_id', models.CharField(blank=True, default='', max_length=200, verbose_name='应用ID')),
                ('encrypted_secret', models.TextField(blank=True, default='', verbose_name='加密密钥')),
                ('enabled', models.BooleanField(default=False, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '集成配置',
                'verbose_name_plural': '集成配置',
                'db_table': 'integration_configs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('feishu', '飞书'), ('wecom', '企业微信'), ('qqbot', 'QQ机器人'), ('webhook', '通用Webhook'), ('email', '邮件')], default='webhook', max_length=20, verbose_name='服务提供商')),
                ('event_type', models.CharField(max_length=100, verbose_name='事件类型')),
                ('target', models.CharField(blank=True, default='', max_length=200, verbose_name='发送对象')),
                ('payload', models.JSONField(default=dict, verbose_name='发送内容')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='发送状态')),
                ('response', models.TextField(blank=True, default='', verbose_name='返回信息')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '集成日志',
                'verbose_name_plural': '集成日志',
                'db_table': 'integration_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
