# Generated by Django 5.0.6 on 2026-07-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationconfig',
            name='provider',
            field=models.CharField(choices=[('wecom', '企业微信'), ('webhook', '通用Webhook'), ('email', '邮件')], default='webhook', max_length=20, verbose_name='服务提供商'),
        ),
        migrations.AlterField(
            model_name='integrationlog',
            name='provider',
            field=models.CharField(choices=[('wecom', '企业微信'), ('webhook', '通用Webhook'), ('email', '邮件')], default='webhook', max_length=20, verbose_name='服务提供商'),
        ),
    ]
