# Generated by Django 5.0.6 on 2026-07-07 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_webhookconfig'),
        ('projects', '0007_discussion_knowledge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='平台名称')),
                ('platform_type', models.CharField(max_length=50, verbose_name='平台类型')),
                ('api_url', models.URLField(blank=True, default='', verbose_name='API地址')),
                ('api_key', models.CharField(blank=True, default='', max_length=500, verbose_name='API密钥')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='扩展配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '外部平台集成',
                'verbose_name_plural': '外部平台集成',
                'db_table': 'external_platforms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GitRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='仓库地址')),
                ('branch', models.CharField(default='main', max_length=100, verbose_name='分支')),
                ('token', models.CharField(blank=True, default='', max_length=500, verbose_name='访问令牌')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_git_repositories', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='git_repositories', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': 'Git仓库',
                'verbose_name_plural': 'Git仓库',
                'db_table': 'git_repositories',
                'ordering': ['-created_at'],
            },
        ),
    ]
