# Generated by Django 5.0.6 on 2026-07-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('projects', '项目'), ('members', '成员'), ('competitions', '比赛'), ('tasks', '任务'), ('finance', '经费')], max_length=20, verbose_name='导入模块')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('previewing', '预览中'), ('previewed', '已预览'), ('confirming', '确认中'), ('confirmed', '已确认'), ('failed', '失败'), ('rolled_back', '已回滚')], default='pending', max_length=20, verbose_name='导入状态')),
                ('field_mapping', models.JSONField(blank=True, default=dict, verbose_name='字段映射')),
                ('preview_data', models.JSONField(blank=True, null=True, verbose_name='预览数据')),
                ('snapshot', models.JSONField(blank=True, default=list, verbose_name='写入快照')),
                ('total_rows', models.IntegerField(default=0, verbose_name='总行数')),
                ('valid_rows', models.IntegerField(default=0, verbose_name='有效行数')),
                ('error_rows', models.IntegerField(default=0, verbose_name='错误行数')),
                ('error_details', models.JSONField(blank=True, default=dict, verbose_name='错误详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '导入任务',
                'verbose_name_plural': '导入任务',
                'db_table': 'import_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
