# Generated by Django 5.0.6 on 2026-07-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importtask',
            name='module',
            field=models.CharField(choices=[('projects', '项目'), ('members', '成员'), ('competitions', '比赛'), ('tasks', '任务'), ('finance', '经费'), ('ip_applications', '知识产权')], max_length=20, verbose_name='导入模块'),
        ),
    ]
